### ISSUE TITLE
I cannot monitor the received data.

### ISSUE THREAD

**Issue by nopnop2002** [TheRaptus/USB-CAN-Adapter#1]
Thank you for a great job.

I was able to send data using this tool.

But I cannot monitor the received data.

Do you have any advice?

![Can2Usb-1](https://user-images.githubusercontent.com/6020549/86437829-4f0c8a80-bd40-11ea-9d24-5248a55769a8.jpg)

![Can2Usb-2](https://user-images.githubusercontent.com/6020549/86437839-57fd5c00-bd40-11ea-8e0c-83f4fad8b628.jpg)

![Can2Usb-3](https://user-images.githubusercontent.com/6020549/86437845-5b90e300-bd40-11ea-83cb-673f97c702d7.jpg)

![IMG_0708](https://user-images.githubusercontent.com/6020549/86438041-bfb3a700-bd40-11ea-94a2-ce633d3fb9dc.JPG)

**Comment by moltonim** [comment]
Hi!
Happy to see that someone is interested on it!
I'm sorry but after this testing program I lost the adapter (stolen) and never used again. SO i delete the program and dismissed the developement, due to lack of interest. Honestly I don't remeber (after 4 years!) if it was comlete or not.
In the setting page Try to fix a address interval (the largest possible) and see if you receive something. Then reduce the interval: the idea was to apply some filter to focus only on a restricted area. 
But the program was comlete and running, unfortunately I can't maintain it whitout the device.

**Comment by nopnop2002** [comment]
Thank you for your reply.

I understood.
